ryanatkn/gro

changelog.md
src/utils/createObtainable.test.ts
src/utils/createObtainable.ts

This adds a utility function that was needed for Felt's database tasks. ([this impermanent link works for now to see its usage](https://github.com/feltcoop/felt/commit/202f8494d539cb528c84e5a31e16332e46f30a86#diff-ebc46f16dd98026100a75a4423088092R8)) The use case was the `db/create` task which composed `db/destroy`, `db/migrate`, and `db/seed`. Each of those tasks needs to separately obtain a database connection and tear it down when finished. However we only want to tear down the connection once, not between each sub-task.
As a higher order function, its type is fairly complex, but it's nicely reusable and well tested. 
~~A future improvement could have the `release` function always return a promise that's called when the obtained thing is fully released. I didn't need it now, so I kept …

add createObtainable for decoupled lifecycle management

---

changelog.md
src/cli/invoke.ts

This change allows any projects using Gro to bootstrap without first building TypeScript. This simplifies CI and first-time setup. CI for Felt can be simplified from `npm run build`, which does `tsc && gro build`, to simply `gro build` without any additional changes.

ensure the project has been built when invoking tasks

---

tsconfig.json

This cleans up some of the TypeScript config and makes it match Felt's. Behavior should be the same except it's now down-compiled to ES2018.

clean up tsconfig

---

src/utils/createObtainable.test.ts
src/utils/createObtainable.ts

This is purely aesthetic change. Previously the `createObtainable` helper used the term "release" for letting go of an obtained reference, but it's an overloaded term that muddies up searches, so I went with the less grammatical but more straightforward "unobtain".

rename the overloaded term release to unobtain

---

src/oki/report.ts

This is a purely aesthetic change. Some old code previous used the terminology "format" to turn values into printable strings, and at some point I renamed the [format utilities](https://github.com/feltcoop/gro/blob/master/src/utils/print.ts) to use "print" instead. The utilities here were left out of that change unintentionally, and since we added `gro format` they conflict in searches, so this PR makes them consistent.

rename some internal print helpers

---

README.md
changelog.md
src/project/clean.ts

This changes the `gro clean` task to remove directories entirely instead of just emptying them. Gro's current heuristic for performing a compilation when running a task currently just looks for the presence of a build directory.
Previously, running `gro clean && gro <task>` as a user would not trigger compilation, but with this change it does.
Although the heuristic leads to problems in some circumstances, it's a fine solution for now. The fix is to just run `gro clean`.

make the clean task remove directories instead of emptying them

---

changelog.md
src/cli/invoke.ts

This improves a heuristic to detect if we want Gro to compile TypeScript when it tries to run a task. Previously it looked for the presence of the `build/` directory, and now it looks for the actual target task file in `build/`. Typically `gro dev` takes care of all of this for the developer, but this helps cover usage outside of that normal happy path.
PR #11 changed `gro clean` to remove directories completely to accommodate the old heuristic, rather than simply emptying the directories like it did before. Although that's no longer needed, because it now looks for the specific task file, I think it's still good behavior to fully remove the `build/` and `dist/` directories. Feels cleaner for sure. 🧹🧹

check full task path to see if compilation is needed

---

README.md

Most projects have a separate CLI but I didn't want the complication. Long term that's probably the better thing to do.
Peer dependencies are currently a wart, printing out a bunch of warnings on installation, but [npm 7](https://blog.npmjs.org/post/618653678433435649/npm-v7-series-arborist-deep-dive) should eliminate that issue.

add install docs

---

changelog.md
src/check.task.ts
src/gen.task.ts
src/gen/genModule.test.ts
src/gen/genModule.ts

We have a widely useful task in `gro check` that wraps up the following:
- typechecks
- runs tests
- checks formatting
- checks generated files are not stale
The last one is a bit tricky because some projects might not use Gro's file generation, but we still want `gro check` to be convenient. We usually want `gro gen` to fail loudly if there's nothing to generate. This adds the optional flag `okIfNone` to the gen task to suppress errors specifically when no files are found, instead printing a helpful diagnostic and exiting quietly. It's then used in the `gro check` task.
I considered not using a flag and instead using the heuristic that if you do `gro gen` it'll not error, but `gro gen dirWithNoGenFiles` would error, but opted for the more explicit, less surprising flag route.
I tried to …

check generated files only when some exist

---

changelog.md
src/format.task.ts

This adds an additional glob to the default formatter to include some files in the root directory. Which files to target is a bit tricky. Generally speaking, Gro expects everything to be in your `src/` directory, but it's common to have some files in the root directory for various tools, and we want a subset of those to be formatted. We don't want to format things like `package-lock.json` or `package.json` because those are modified directly by npm. Insead of adding a blacklist, I opted to just target TypeScript, JavaScript, and Markdown files. Seems ok?

format files in the root directory

---

changelog.md
src/cli/invoke.ts

This fixes Gro's heuristic that detects if a project should have its TypeScript compiled during a task invocation. It worked in the intended cases except when a user project invoked a Gro builtin task - in that case the it detected that Gro's version of the task was built, but the current project may not be. Now it looks for the presence of a `build/` directory in the current project.
This is really just a best-effort detection heuristic. Properly detecting if a project needs to be built when invoking a task is too expensive to perform each time - it would significantly impact startup time. Generally speaking, the developer should be expected to call `gro dev` or `gro build` to ensure their tasks are correctly refreshed. The primary purpose of this detection is initial setup, CI, and …

fix unbuilt project detection when invoking builtin Gro tasks

---

changelog.md
src/cli/invoke.ts
src/paths.test.ts
src/paths.ts

This fixes what I thought I fixed in #16. There was a subtle bug in how the code differentiated between Gro and app file paths.

properly detect build status when invoking builtin Gro tasks

---

changelog.md
src/check.task.ts
src/oki/testModule.ts
src/test.task.ts

This mirrors what #13 did for gen files, but with tests. Previously the check task would error out if the project has no tests. I ran into this while dogfooding Gro on a fresh project today. (it revealed other rough edges, but overall I give all my thumbs up 👍👍👍)
Again this is not efficient, but we're only talking about a few milliseconds for most projects, and before Felt grows too large, we'll want to implement a virtual filesystem for lots of reasons, which will solve the performance issue.

change check task to run tests only if some exist

---

changelog.md
src/oki/README.md
src/oki/assertions.test.ts
src/oki/assertions.ts
src/oki/report.ts

This adds the async test assertion `rejects` to complement the synchronous `throws`. I needed it for Felt. The tests for `rejects` might make your eyes glaze over (they did to me), but they're pretty simple - just copy/pasted from the `throws` tests with `async` sprinkled in, with two cases added to test promise arguments.
It also cleans up some things and removes some ancient test code that was being ignored.

add async rejects assertion

---

changelog.md
src/assets.task.ts
src/check.task.ts
src/cli/invoke.ts
src/dev.task.ts
src/dist.task.ts
src/docs/tasks.md
src/gen/README.md
src/project/build.task.ts
src/project/dist.task.ts
src/project/link.task.ts
src/serve.task.ts
src/task/README.md
src/task/invokeTask.ts
src/task/runTask.test.ts
src/task/runTask.ts
src/task/task.ts

This adds the `invokeTask` helper to compose tasks. It's now the preferred way to run tasks within other tasks. See [`src/task/README.md`](https://github.com/feltcoop/gro/compare/invoke-task?expand=1#diff-ebdf9b0ad317ea3f4bc6180e382d4bc4) for the new documentation.
The motivating use case was that the builtin check task did not account for the user overriding any of its sub tasks. Directly importing and running tasks from within builtin tasks is usually not what we want. For end users, it matters less, but they probably want to prefer `invokeTask` over explicit task imports because it provides good logging and diagnostics. The docs linked above go into more detail.
It might look like there are a lot of changes but there's not much to it, helped by the fact that the code was already …

add the invokeTask helper for task composition

---

README.md
changelog.md
src/task/invokeTask.ts

This makes `gro --version` and `gro -v` just print the Gro version. We don't yet support sophisticated CLI flag processing so it's low tech. Currently we just leave everything to the individual tasks but that will probably change in the future.

add --version and -v CLI flags to print the Gro version

---

changelog.md
src/oki/assertions.ts
src/utils/object.test.ts

This is a small change that adds a bit of type safety to Gro's assertions. It makes `t.is` and `t.equal` share a generic type so incompatible types will surface an error.
Occasionally it'll have a false positive that can be trivially fixed with a cast to `any`, [as is needed here](https://github.com/feltcoop/gro/compare/improve-assertions-types?expand=1#diff-670184333154c7b9a93145aba7ea382dR44).

improve type safety for assertions

---

changelog.md
src/project/rollup-plugin-gro-typescript.ts

This fixes JS module resolution in the TypeScript plugin. Previously we were importing `.ts` files directly [which will hopefully be supported by TypeScript soonish](https://github.com/microsoft/TypeScript/issues/38149), but isn't right now.

fix .js module resolution in the Rollup TypeScript plugin

---

changelog.md
src/project/rollup-plugin-gro-typescript.ts

This fixes Node module resolution that #24 missed. See the added comments for more.

fix js module resolution for external paths in typescript plugin

---

changelog.md
package-lock.json
package.json
src/colors/terminal.ts
src/devServer/devServer.ts
src/fs/modules.ts
src/gen.task.ts
src/gen/runGen.ts
src/oki/TestContext.ts
src/oki/report.ts
src/project/assets.ts
src/project/build.ts
src/project/cssCache.ts
src/project/fileCache.ts
src/project/globalTypes.d.ts
src/project/rollup-plugin-diagnostics.ts
src/project/rollup-plugin-gro-json.ts
src/project/rollup-plugin-gro-svelte.ts
src/project/rollup-plugin-gro-terser.ts
src/project/rollup-plugin-gro-typescript.ts
src/project/rollup-plugin-output-css.ts
src/project/rollup-plugin-plain-css.ts
src/project/svelte-preprocess-typescript.ts
src/project/tsHelpers.ts
src/task/invokeTask.ts
src/task/runTask.ts
src/utils/log.ts
src/utils/print.ts
src/utils/process.ts

This upgrades the `kleur` dependency to v4 which now provides ES modules. We can remove our wrapper code and import from `kleur/colors` directly now. It's a breaking change so it bumps Gro to v0.2.0. I was on the fence about supporting fancy RGBA colors later on, like via Chalk, but that's such a low priority and this keeps things simple and fast.

 upgrade kleur and remove color wrappers 

---

changelog.md
src/globalTypes.ts

This adds a couple of primitive type helpers that we'll try to use in Felt. This pattern is often called "branding" among TypeScript developers. I want to think about the names a bit more. `Primitive` might be the wrong way to think about them, since you could technically brand any type. Maybe `Nominal` and `StrictNominal`? Or `Brand` and `StrictBrand`? Or reverse them and use "Loose"? I've also seen the optional kind named `Flavor`, so `Brand` would be strict.

add primitive type helpers

---

changelog.md
src/colors/terminal.ts
src/devServer/devServer.ts
src/fs/modules.ts
src/gen.task.ts
src/gen/runGen.ts
src/oki/TestContext.ts
src/oki/report.ts
src/project/assets.ts
src/project/build.ts
src/project/cssCache.ts
src/project/fileCache.ts
src/project/rollup-plugin-diagnostics.ts
src/project/rollup-plugin-gro-json.ts
src/project/rollup-plugin-gro-svelte.ts
src/project/rollup-plugin-gro-terser.ts
src/project/rollup-plugin-gro-typescript.ts
src/project/rollup-plugin-output-css.ts
src/project/rollup-plugin-plain-css.ts
src/project/svelte-preprocess-typescript.ts
src/project/tsHelpers.ts
src/task/invokeTask.ts
src/task/runTask.ts
src/utils/log.ts
src/utils/print.ts
src/utils/process.ts

This exports all of the `kleur/colors` module from `src/colors/terminal.js` so dependents don't need to add an extra dependency. It's common enough to want to use terminal colors in an app, and since Gro already includes `kleur` as a runtime dependency it makes sense to just re-export them.

export kleur colors for external usage

---

changelog.md
src/fs/modules.ts
src/globalTypes.ts
src/oki/TestContext.ts

This adds the `Result` type helper [discussed here for Felt](https://github.com/feltcoop/felt/pull/33#discussion_r451855156). It's simple and doesn't do much, but it formalizes a common pattern that I found myself duplicating a helper for in multiple projects.
I decided to err on the side of flexibility over a more rigid convention. This avoided needing to change any of Gro's functional code (only some type definitions changed), and I currently prefer its usage of `Result` values that are flat objects without nested `value`/`error` properties.
We can still use this type to write generic functions, but instead of always assuming a `value` or `error` property, it's flexible enough to work for any properties, so its functionality is a superset of option 4 described in the above link. Here's …

add Result type helper

---

changelog.md
package-lock.json
package.json
src/utils/uuid.test.ts
src/utils/uuid.ts

This wraps `@lukeed/uuid` with a flavored type and validation function. It includes a comment explaining why we're not using the `ajv` UUID validation regexp. (`ajv` isn't yet added as a dependency, but it will be soon)

add uuid utilities

---

changelog.md
src/project/build.ts

I don't remember why sourcemaps are turned off, but turning them on for development seems to work without any more changes.

enable sourcemaps for build in development mode

---

changelog.md
src/build.task.ts
src/cli/types.ts
src/project/build.ts
src/project/cssCache.ts

This makes the Rollup build extensible through the introduction of three optional mapping functions that can transform the `InputOptions`, `OutputOptions`, and `RollupWatchOptions` however they wish. This should give consumers a lot of control without directly exposing Rollup, allowing Gro to use a faster tool during development like [Nollup](https://github.com/PepsRyuu/nollup/) or [Vite](https://github.com/vuejs/vite) in the future.
The main behavioral change is that it separates the Svelte and plain CSS bundles into separate ones to fix source maps. These could be combined back into one if we generated a source map for all plain CSS, but currently no consumer projects need that.

make Rollup build extensible

---

changelog.md
src/project/rollup-plugin-output-css.ts

This sorts CSS builds to make the output deterministic. Without this sorting, things like Svelte component CSS may appear in random order, making deployments non-deterministic and therefore uncacheable.

sort CSS builds to make output deterministic

---

changelog.md
src/check.task.ts

This ensures that the `gro check` task always starts from a clean slate. Previously, stale build files could cause incorrect checks.

run the clean task at the beginning of the check task

---

src/dev.task.ts

The default `gro dev` task now builds TypeScript to the `build/` directory. The build process is still a work in progress - this only affects running `gro` commands right now, as the default `gro build` task doesn't use the `build/` directory artifacts yet.

build TypeScript in the dev task

---

changelog.md
src/deploy.task.ts
src/docs/tasks.md

This adds the `gro deploy` task for deployment of static builds to GitHub pages via the `gh-pages` branch. We can make it more configurable in a followup PR. It uses Git worktrees to simplify the process of managing a clean `gh-pages` branch with history without polluting anything outside of that branch.

add a default deploy task for gh-pages

---

changelog.md
src/deploy.task.ts

This makes the `gro deploy` command delete the `dist/` directory once it's finished. The reasoning is that it uses the git worktree feature to simplify branch management for deployment, and since it uses the same `dist/` directory as development, it's likely to be confusing and error-prone.
We may want to revert this change and create a special `deploy/` directory instead of re-using `dist/`.

change the deploy task to delete dist when done

---

changelog.md
src/task/invokeTask.ts

This fixes the log message label when no task is provided. Before it prints `[undefined]` and now it'll be `[gro]`.

fix log message when listing all tasks

---

changelog.md
src/deploy.task.ts

This makes the deploy task, which handles static deployments (currently hardcoded to GitHub pages), more robust by properly cleaning up if the build fails. It also adds the `--dry` flag, e.g. `gro deploy --dry`, to optionally preserve the build files and makes no remote changes to any git repos, which is helpful for diagnostic purposes.

handle build errors in the deploy task and add the dry flag

---

changelog.md
package-lock.json
package.json
src/docs/tasks.md
src/fs/nodeFs.ts
src/project/build.ts
src/project/compilerBenchmark.task.ts
src/project/rollup-plugin-gro-swc.ts
src/project/svelte-preprocess-swc.ts
src/project/svelte-preprocess-typescript.ts
src/project/swcHelpers.ts
tsconfig.json

This adds a new dependency, [swc](https://github.com/swc-project/swc), which is an alternative to compilers like Babel and TypeScript. We will continue using the TypeScript compiler for typechecking and for generating type mappings in production builds, but I believe everything else can be migrated over to use `swc` with no impact except 20-100x faster builds.
This is the first PR to integrate `swc`, and the main thing it adds are a Rollup plugin and Svelte preprocessor. There's also a benchmark task that shows the 20-100x speedup. I was planning a revamp of various pieces of the tools and tasks Gro has for building code, and I think this is a good time to do that work. I'll probably make several smallish PRs over the next couple months, and likely at least one big one that introduces a …

add swc rollup plugin and svelte preprocessor

---

changelog.md
src/compile/compile.ts
src/fs/modules.ts
src/gen.task.ts
src/gen/runGen.ts
src/oki/TestContext.ts
src/task/invokeTask.ts
src/test.task.ts
src/utils/time.test.ts
src/utils/time.ts

This adds a feature to `Timings`. `Timings#start` now returns a callback that does the same thing as calling `Timings#stop` with the same key. This new API should be preferred in the general case because it relies on the TypeScript language to ensure the callback gets called at least once and with the same key. The old API duplicates keys and has no language-level help for ensuring they get called, which can be errorful when refactoring. The old API is still useful when keys are programmatically defined, which Gro uses in several places, e.g. tracking the timings for many generated files.

add stop function return value to timings api

---

changelog.md
src/fs/mime.test.ts
src/fs/mime.ts
src/paths.test.ts
src/paths.ts
src/project/rollup-plugin-gro-svelte.ts
src/project/rollup-plugin-gro-swc.ts
src/project/rollup-plugin-gro-typescript.ts
src/project/rollup-plugin-plain-css.ts
src/utils/path.test.ts
src/utils/path.ts

The preference I've shifted towards with your influence is to fully write out the names of things in most cases, and "ext" for "extension" is one of the last remaining examples that doesn't follow the newer pattern. Node and Unix use "ext" a lot but this fits the codebase better.

rename identifiers from ext to extension

---

changelog.md
src/oki/assertions.test.ts
src/oki/assertions.ts
src/oki/report.ts

This is a small breaking change that converts the `AssertionOperator` in the testing framework from a string enum to a union type of strings. This makes it less verbose and easier for consumers to use, because it no longer requires an explicit import.

convert AssertionOperator from an enum to a union of string types

---

changelog.md
src/oki/TestContext.ts
src/utils/async.ts

This converts the `AsyncState` enum to a string union type and renames it to `AsyncStatus`. The name had been a continuous source of weirdness in consumer code, because "state" is a much less meaningful name than "status". Changing it to a string enum makes it less verbose and easier for consumer code because an explicit import is no longer required.

rename AsyncState to AsyncStatus and convert it to union type

---

changelog.md
package.json
src/build.task.ts
src/compile.task.ts
src/compile/CachingCompiler.ts
src/compile/compileFile.ts
src/compile/compileSourceDirectory.ts
src/compile/swcHelpers.ts
src/compile/tsHelpers.ts
src/dev.task.ts
src/fs/modules.ts
src/fs/watchNodeFs.ts
src/paths.test.ts
src/paths.ts
src/project/build.task.ts
src/project/build.ts
src/project/dev.task.ts
src/project/rollup-plugin-diagnostics.ts
src/project/rollup-plugin-gro-swc.ts
src/project/svelte-preprocess-swc.ts
src/project/svelte-preprocess-typescript.ts
src/task/invokeTask.ts
src/typecheck.task.ts
src/utils/path.ts

This adds the `src/compile/CachingCompiler.ts` module which replaces the TypeScript compiler watch mode `tsc -w` with `swc`. It's designed to avoid writing to disk and caches compiled files from `src/` to `build/`. I held back on adding too many options and extension points until they're driven by use cases. It currently does not handle Svelte (or any other compilers that product multiple files from one input file), but it'll speed up development wherever `tsc -w` was used, which was in both Gro and Felt.

add caching compiler to replace tsc watchmode with swc

---

changelog.md
package.json
src/compile/CachingCompiler.ts
src/compile/compileFile.ts
src/compile/compileSourceDirectory.ts
src/compile/svelteHelpers.ts
src/dev.task.ts
src/paths.test.ts
src/paths.ts
src/project/build.ts
src/project/cssCache.ts
src/project/dev.task.ts
src/project/rollup-plugin-gro-svelte.ts
src/project/rollup-plugin-output-css.ts
src/project/svelte-preprocess-swc.ts

This adds Svelte compilation to the two unbundled compilation strategies, `compileSourceDirectory` and `CachingCompiler`, which replace `tsc` and `tsc -w` respectively during development. Gro already supports Svelte compilation through its Rollup plugin, but we're moving toward unbundled compilation during development (inspired by [Snowpack](https://www.snowpack.dev/)), and this is an important step, although the usecases it's designed for need more pieces finished before they're ready. The PR also significantly refactors `CachingCompiler`.

add svelte compilation to the unbundled compilation strategies

---

src/compile/compiler.ts
src/devServer/devServer.ts
src/fs/Filer.ts

This renames some of the `Filer` and `Compiler` types. It also changes the `Filer`'s compiled file type to wrap compilations instead of extending them. This provides a cleaner separation between the compiler's return value and all of the subsequent metadata that we add (there will be more in the future), at the cost of some duplication of properties.
This is in preparation for the postprocess step which makes the compiled file's contents potentially diverge from the original compilation's, and by storing the original reference, we retain the un-postprocessed version. We need to postprocess files to update their module paths to support Svelte and other usecases. I currently like the idea of isolating the `Compiler` to not touch module paths, just like the TypeScript and Svelte compilers.

refactor filer types

---

package-lock.json
package.json
src/fs/Filer.ts

This adds a new dependency, [`es-module-lexer`](https://github.com/guybedford/es-module-lexer), which is a tiny and super fast tool for extracting the import information from a JS module. The added `postprocess` function takes a compilation and uses `es-module-lexer` to change Svelte imports from `*.svelte` to `*.js`. There's a lot more work that needs to be done to make Gro support Svelte in the browser, but this is a significant step because it demonstrates high performance rewriting of import paths. We'll further refactor this code but it makes sense to merge this piece now.

postprocess compiled files to change svelte imports to js

---

changelog.md
src/compile/compileSourceDirectory.ts
src/compile/compiler.ts
src/compile/defaultCompiler.ts
src/compile/svelteCompiler.ts
src/compile/swcCompiler.ts
src/dev.task.ts
src/fs/Filer.ts
src/project/dev.task.ts
src/serve.task.ts

This refactors `createCompiler` to allow users to select a compiler for each file. This makes it extensible in a very flexible way. The PR also adds the `defaultCompiler.ts` module which removes the boilerplate from the normal case.

make the compiler pluggable

---

changelog.md
src/compile/compileSourceDirectory.ts
src/compile/compiler.ts
src/compile/svelteCompiler.ts
src/compile/swcCompiler.ts
src/dev.task.ts
src/dist.task.ts
src/fs/Filer.ts
src/paths.ts
src/project/clean.ts
src/project/dev.task.ts

This is a minor change that clarifies the concepts of the `Filer`. It now takes an optional `buildRootDir` that defaults to `paths.build`, the `.gro` directory. Previously each source directory stored its own build root directory, which is more flexible, but it's complex and unnecessary with current use cases. We may want the flexibility back in the future, but I am guessing that there's a better design to accomplish that. This change simplify interfaces at multiple levels.

move the buildRootDir from source files to the Filer

---

changelog.md
src/build.task.ts
src/build/Filer.ts
src/build/postprocess.ts
src/compile/compiler.ts
src/compile/externalsCompiler.ts
src/compile/svelteCompiler.ts
src/compile/swcCompiler.ts
src/compile/swcHelpers.ts
src/compile/tsHelpers.ts
src/dev.task.ts
src/project/dev.task.ts

This adds simple caching to the `Filer`'s build options. When the `Filer` initializes, it tries to load any previously cached build options, and if it either can't find them or they've changed, it clears all existing builds. This means that if you toggle source maps, modify the `BuildConfig`s, or change other `CachedBuildOptions`, we're sure to have clean and correct builds. Its cache invalidation is fairly aggressive, opting for simplicity and correctness over optimal preservation of valid build artifacts. Basically, if the developer changes any of the `CachedBuildOptions`, they'll need to re-run `gro dev` and wait for the cold cache to warm up as it performs a complete rebuild.
To make this work, build options are hoisted out of the `Compiler` implementations into the `Filer` and passed …

cache build options and invalidate builds when options change

---

README.md
src/docs/README.md
src/docs/unbundledDevelopment.md

This documents the unbundled development features added for v0.5.0. There's an emphasis on comparing Gro's dev system to [Snowpack](https://github.com/pikapkg/snowpack), which heavily inspired it.

add docs for unbundled development

---

.vscode/launch.json
src/build/Filer.ts
src/build/buildFile.ts
src/build/sourceFile.ts
src/utils/object.ts

This adds tracking of source file dependencies. Unknown source files have their `id` inferred and can now be added after the `Filer` starts up.

track source file dependencies

---

src/build/builder.ts
src/build/externalsBuilder.ts

This fixes an oversight in the externals builder. The `target` - the version of ECMAScript that's output - was already available in the options, and additional overriding per build config will be left to a later commit.

use the target option

---

src/build/buildSourceDirectory.ts
src/compile.task.ts
src/config/config.ts
src/dev.task.ts
src/dist.task.ts
src/gro.config.ts
src/project/dev.task.ts
src/task/invokeTask.ts
src/utils/log.ts

This moves three variables from random bits of code to the Gro config, the ECMAScript `target`, boolean `sourceMap`, and `LogLevel` `logLevel` for the main and Gro system loggers. These new options are not required - pass `undefined` to get their default values, or just omit them from config objects.

move target, sourceMap, and logLevel to the gro config

---

changelog.md
src/build/Filer.ts
src/devServer/devServer.ts
src/fs/mime.test.ts
src/fs/mime.ts

This adds content-based caching to the dev server using [ETags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) and the contents hash functionality the `Filer` already provided.
I'm not sure what the best header values are here, like for `'Cache-Control'`. I left some comments for followup investigation - nothing blocking. I'm testing in Firefox and Chrome, and currently, things look correct except Chrome is not sending the `'if-none-match'` header for `.map` source map files, so those are always returning a 200 instead of 304 right now. Can't find anything to fix that in a brief search - they're always being requested with "no-cache" header values. Works in Firefox.

add 304 caching with etags

---

src/server/server.ts

Previously, if Gro was run a second time on the same port, it would just crash. Now it searches downward from the default port until it finds its own personal port.

decrement server port until an open one is found

---

src/check.task.ts
src/task/invokeTask.ts

This dramatically improves Gro CLI startup time for most usage. The changes are trivial, too, and have no real downsides. I've been thinking there could be gains here since I implemented this code originally - code to lazy-build a Gro project's tasks - but I didn't think the gains would be this big. Makes me wonder how much of the remaining 0.15-0.2s we could shave off. I know that's an eternity in Real CLI land, but for Node/TypeScript I'm alright with that overhead. Or at least, it's not keeping me up tonight - I might get inspired to look for more gains.
`$ time gro project/echo hey`
before:
```
gro project/echo hey 0.58s user 0.08s system 118% cpu 0.557 total
gro project/echo hey 0.66s user 0.04s system 127% cpu 0.554 total
gro project/echo hey 0.60s user 0.07s system 119% cpu 0.560 …
```

lazy load modules to speed up normal invoke task case

---

changelog.md
src/config/config.ts
src/dev.task.ts
src/docs/config.md
src/gro.config.ts

This adds some documentation about the Gro config.
It also renames the config property `servedDirs` to `serve`, which is a friendlier external name. The precedent for breaking external naming conventions from internal ones was established with `builds` for `buildConfigs` - nobody wants to write `buildConfigs`, we want to write `builds`, but internally in Gro we really prefer to be explicit that these are `BuildConfig`, and not `Build` objects, which are very different.

document and rename the serve config property

---

src/build/Filer.ts
src/task/README.md

This fixes the handler for when source files were deleted. It correctly removes them from their builds now.

fix destroying source files

---

changelog.md
package-lock.json
package.json
src/build/Filer.ts
src/build/builder.ts
src/build/externalsBuildHelpers.ts
src/build/externalsBuilder.ts
src/build/postprocess.ts
src/client/SourceMetaExpanderItem.svelte
src/client/SourceMetaRawItem.svelte
src/client/index.ts
src/client/styles.css
src/fs/importTs.ts

This adds alias support for externals. The motivating use case is swapping `path-browserify` for `path` so it works in the browser.

add alias support to externals

---

changelog.md
src/build/externalsBuilder.ts

This lets users provide an optional `install` function to the externals builder. The idea is to give defer full control if the user code wants it, but provide the default. Users can now intercept the install arguments before forwarding them, or call a custom `install` function, or whatever.

add install option to externals builder

---

changelog.md
src/config/config.ts
src/config/gro.config.default.ts
src/dev.task.ts
src/docs/config.md
src/serve.task.ts
src/server/server.ts

This adds the `port` and `config` options to the Gro config.

add port and host config options

---

src/build.task.ts
src/build/Filer.ts
src/build/buildFile.ts
src/build/buildSourceDirectory.ts
src/build/builder.ts
src/build/esbuildBuilder.ts
src/build/externalsBuilder.ts
src/build/svelteBuildHelpers.ts
src/build/svelteBuilder.ts
src/build/utils.ts
src/cli/invoke.ts
src/config/config.ts
src/dev.task.ts
src/docs/config.md
src/fs/importTs.ts
src/gen/README.md
src/project/build.ts
src/project/rollup-plugin-gro-esbuild.ts
tsconfig.json

I previously went with the `sourceMap` convention instead of `sourcemap` to match TypeScript, but Svelte, Rollup, and esbuild use the latter, and we want to follow their lead in these cases. This is one of those things that's generally inconsistent - e.g. Rollup and others export types with `SourceMap` in the name, and TypeScript has "type maps" which suggest it's a two word thing, but.. `sourcemap` it is.

sourcemap is one word now

---

src/build/buildFile.ts
src/build/builder.ts
src/build/esbuildBuilder.ts
src/build/externalsBuilder.ts
src/build/svelteBuilder.ts

This was used during the `Filer`'s development but it's no longer used, and sourcemaps can be cheaply duck-typed if it's ever needed: we should be able to safely assume the build file is the same but without the suffix `.map`.

remove the sourcemapOf build file property

---

.gitignore
README.md
changelog.md
src/cert.task.ts
src/dev.task.ts
src/docs/tasks.md
src/serve.task.ts
src/server/README.md
src/server/https.ts
src/server/server.ts
src/task/runTask.ts

This adds http2 and https support to the dev server. I was hoping it would speed up loading pages with large module waterfalls, but so far it seems like slows things down by 10-20%. I'm not sure if this is due to an oversight in the code, or if http2 just won't speed up this use case. If the latter is the case, a better long term situation is to probably use the `cache-control: immutable` header as much as possible, though we need import maps for that: WICG /import-maps/issues/146

add http2 and https support to the dev server

---

changelog.md
src/build/Filer.ts

This removes a check that disallowed removing build configs from source files that are inputs. The logic to properly keep input files is working, so this check did nothing except incorrectly throw when an input file is deleted from the source tree.

allow deleting input files

---

changelog.md
src/serve.task.ts
src/server/server.ts

The Gro dev server is designed to be as useful as it can be in development mode, and this means it might have security holes in a production environment. For now it will throw unless the `NODE_ENV === 'development'`. It's for our own good!!

restrict dev server to development usage

---

changelog.md
tsconfig.json

This reverts the TypeScript setting `importsNotUsedAsValues` to "remove". This seems much better for TypeScript files than "error".

set importsNotUsedAsValues to remove

---

changelog.md
src/paths.ts

Fixes a regression that broke import paths. It broke external user scripts!
So yeah we need better tests.

fix import path

---

changelog.md
src/dev.task.ts

This adds some optional hooks to `src/dev.task.ts`, the main dev task. It lets user code get some juicy inside bits.
This is in service of a larger goal, to let external user code implement an automatic server restarter. We'll experiment with that API, but this is a good start.

dev task hooks

---

changelog.md
src/build/Filer.ts

This improves the error message when a build config input is missing. The bare assertion isn't very helpful!

improve input error

---

changelog.md
src/build/Filer.ts
src/build/ServedDir.ts
src/build/formatFile.ts
src/build/svelteBuildHelpers.ts
src/cli/types.ts
src/client/pathHelpers.ts
src/config/buildConfig.ts
src/config/config.ts
src/fs/inputPath.test.ts
src/fs/modules.test.ts
src/fs/modules.ts
src/fs/testModule.ts
src/fs/watchNodeFs.ts
src/gen/genModule.ts
src/globalTypes.ts
src/index.ts
src/project/build.ts
src/project/packageJson.ts
src/project/rollup-plugin-gro-esbuild.ts
src/project/rollup-plugin-gro-svelte.ts
src/project/rollup-plugin-output-css.ts
src/project/rollup-plugin-plain-css.ts
src/server/server.ts
src/task/taskModule.ts
src/types.ts
src/utils/object.ts
src/utils/uuid.ts

With this **breaking** change, Gro no longer exports global types like `Result` and `Flavored`. They are all available on the root, so:
```ts
// all previously global types are now exported
import type {Result} from '@feltcoop/gro';
```
I like the convenience of global types, but it feels arrogant (better word?) to use them. Gro will play by the same rules that it expects everyone else to follow.
If you have the following in your `tsconfig.json`, remove it, since it's no longer needed:
```json
{
"compilerOptions": {
"types": ["@feltcoop/gro"]
}
}
```

break: change global types to root exports

---

changelog.md
src/utils/types.ts

This adds the the `unwrap` type helper to `src/utils/types.ts`. The idea is that it extracts the value of a wrapped `Result` that you expect to be `ok`. If it's not `ok`, it'll throw. The design is inspired by Rust.
The type looks gnarly but it's easy to use. You shouldn't need any explicit annotations, just past it a `Result`. The type also may be improvable.

add unwrap Result type helper

---

changelog.md
src/build/Filer.ts
src/config/gro.config.default.ts

Gro's SPA behavior is now deprecated as we think long term about offering an alternative in SvelteKit to Vite. This changes the default to only include a Gro browser build if that project form is detected. Otherwise, no browser build is created, and SvelteKit with Vite own any frontend completely.

detect deprecated SPA projects and handle gracefully

---

changelog.md
src/build/Filer.ts
src/config/gro.config.default.ts
src/docs/config.md

This changes the default build config to detect if there's a `server/server.ts` file. If so, it'll add it as an entry point to the primary Node build. As always, projects can define their own config and builds at `src/gro.config.ts`.

detect default server build

---

src/project/build.task.ts

This cleans the Gro `dist/` at the beginning of the production build. Previously, the important code paths were cleaning properly, but `gro project/build` did not, causing confusion.

fix: clean before production build

---

README.md
changelog.md
package.json
src/build.task.ts
src/build/esbuildBuildHelpers.ts
src/build/esbuildBuilder.ts
src/build/externalsBuilder.ts
src/build/svelteBuildHelpers.ts
src/build/svelteBuilder.ts
src/check.task.ts
src/cli/invoke.ts
src/config/config.ts
src/deploy.task.ts
src/dist.task.ts
src/env.ts
src/format.task.ts
src/gen.task.ts
src/project/build.task.ts
src/project/build.ts
src/serve.task.ts
src/server/https.ts
src/server/server.ts
src/task/fixtures/testFailingTaskModule.ts
src/test.task.ts
src/typecheck.task.ts
src/utils/env.ts
src/utils/lazy.ts
tsconfig.json

Inspired by SvelteKit, Gro finally made a decision about how to handle the development/production switch, aka `process.env.NODE_ENV` and `import.meta.env.DEV`. It's nice when others make great decisions for you.
Modules should use `import {dev} from '@feltcoop/gro/dist/env.js'` for now. (the `dist/` goes away with TypeScript 4.3 soon) It uses the same pattern as SvelteKit, using `import.meta.env.DEV`. Internally it replaces the values at buildtime using `esbuild`'s [`define`](https://esbuild.github.io/api/#define).

add env support

---

changelog.md
package-lock.json
package.json
src/build/Filer.ts

This changes the `Filer` to extend `EventEmitter` and emit a `'build'` event for each source file and build config that gets built.
The motivating usecase is to let usercode implement a server restart feature. This seems like a good API direction for the `Filer` to go to minimally support this. We'll consider more events as they're needed.

filer event emitter

---

changelog.md
package-lock.json
package.json

This changes Gro's type definition dependencies to be regular dependencies, not dev only. User code sometimes needs these types when they're transitively exposed, so I'm doing the safe thing and shipping all of them unless I know for sure it won't be exposed to users.

change type deps to regular deps

---

README.md
changelog.md
src/docs/tasks.md
src/version.task.ts

This implements a basic `gro version` task. So you might run `gro version patch` to sweep a bug under the rug.
The idea is that it defers to [npm version](https://docs.npmjs.com/cli/v6/commands/npm-version) as much as possible, adding simple scripting around it without getting in the way. (see the line where it forwards raw args)
In short, it runs the production build, publishes to npm, and syncs commits and tags to GitHub. It could be improved, but probably through the `gro.config.ts` in addition to CLI args. Something to think through another day.
It was motivated by a sleepy developer (me) forgetting to switch to the `main` branch when bumping up to 0.7.1. (I think) I fixed it the next day by force pushing, but I believe npm and GitHub will have different version hashes for that tagged …

add version task

---

.github/workflows/nodejs.yml
README.md
changelog.md
package.json
src/build.task.ts
src/version.task.ts

This makes `gro build` work inside of Gro. Previously, Gro used `gro project/build` internally, but now it'll invoke `project/build` if we're inside Gro.
Like with `gro version`, this adds some "task pollution", exposing Gro internals to tasks in `src/` that we want to encourage users to copy/paste. The code is easily removed, but it doesn't look great, and might confuse some users.

make gro build task work for Gro itself

---

changelog.md
src/clean.task.ts
src/dist.task.ts
src/docs/tasks.md
src/paths.ts
src/project/clean.ts

This improves the clean task: it now accepts a number of options. Running it with no options keeps the existing behavior, deleting `/.gro/` and `/dist/`.
- `-B`: keep `/.gro/`, the "Gro build directory"
- `-D`: keep `/dist/`
- `-s`: delete `/.svelte/`
- `-n`: delete `/node_modules/`
It also changes the `clean` function to have a nice options interface.

improve clean task

---

.vscode/launch.json
changelog.md
src/config/gro.config.default.ts
src/dev.task.ts
src/utils/async.ts
src/utils/process.ts

This adds more functionality for the default Gro server, at `src/server/server.ts`. 
First, let's start with moving the server auto-restart behavior from ryanatkn/gro-template-sveltekit-polka to the default Gro task. It is a no-op if no server is detected.

add server auto-restart to dev task

---

changelog.md
src/config/buildConfig.ts
src/config/config.ts
src/config/defaultBuildConfig.ts
src/config/gro.config.default.ts
src/dev.task.ts
src/fs/modules.ts
src/gro.config.ts
src/paths.ts
src/task/invokeTask.ts
src/test.task.ts
src/utils/obtainable.test.ts
src/utils/obtainable.ts

When we set up the builds for our projects with Gro, I wanted to keep things simple, with a single Node build. I designed Gro's build system to be able to hand multiple kinds of builds, even multiple of the same platform, and now it seems we want to use them: specifically, in `src/config/gro.config.default.ts`, we want a Node build with our tasks, tests, etc, and a different Node build with our server, if there is a server.
This allows us to change the API server restart implementation in #129 to no longer wastefully restart when you edit a task, a task dependency, or something or the sort for tests, and other things that are in the primary Node build, but do not cause a change in the API server to warrant restarting it. See the `src/config/gro.config.default.ts` for more.
This is a …

separate the default server and primary Node builds

---

changelog.md
src/build.task.ts
src/build/tsBuildHelpers.ts
src/config/config.ts

This fixes `src/build.task.ts` to correctly use the `sourcemap` and `target` options from the Gro config. It was using the `tsconfig.json` values instead.
I can't tell if we should default to `tsconfig.json` values if there's no Gro config set for `sourcemap` and `target`, or just go with the production toggle and Gro-wide default, respectively. I think I'm fine with the latter on both for now. In case we need it, I'm keeping some relevant code around that's now dead, but would be needed if we use the `tsconfig.json` for more defaults.
This can get weird if you try to use `tsc` for build outputs, but we're not doing that except in Gro itself, and we always ship sourcemaps there, so no worries.
The PR also turns off sourcemaps by default in production. This is the better default for most …

fix build options

---

changelog.md
src/build.task.ts
src/config/config.test.ts
src/config/config.ts
src/dev.task.ts
src/dist.task.ts
src/project/build.task.ts
src/task/README.md
src/task/invokeTask.ts
src/task/runTask.ts
src/task/task.ts
src/test.task.ts

This changes the `dev` value to be optionally declared by `Task`s, and defaults to detecting from `process.env.NODE_ENV` in a single place in `runTask`. I'm not sure this is the final form, but I think it'll fix some issues and be an overall win.

add the optional dev property to task definitions

---

changelog.md
src/task/README.md
src/task/invokeTask.ts
src/task/runTask.ts
src/task/task.ts

This adds the optional `dev` arg to both `invokeTask` and `runTask`. It's inherited but can be overridden by any branch in the task invocation tree.

add the optional dev arg to invokeTask and runTask

---

changelog.md
package.json
src/build/esbuildBuildHelpers.ts
src/task/runTask.ts
src/utils/env.ts

This needs better support or none at all, so for now, none. We'll revisit `import.meta.env.DEV` at another time, and hopefully by then we have figured out `dev` and `process.env.NODE_ENV` once and for all.
This also sets `process.env.NODE_ENV` when running tasks with explicit `dev` values. This was intended but unimplemented, so just very buggy, but technically not breaking? I'm probably wrong.

remove import.meta.env.DEV support and improve process.env.NODE_ENV with tasks

---

changelog.md
src/config/config.ts
src/config/gro.config.default.ts
src/docs/config.md
src/gro.config.ts

This changes `src/gro.config.ts` to export a `config` identifer instead of a `default` export.
It's breaking. Yay, 0.10.0! We've broken through!

change config to export a named config identifer instead of default

---

changelog.md
src/build/Filer.ts
src/build/FilerDir.ts
src/fs/watchNodeFs.ts

This adds the `Filer` option `filter` with type `PathFilter`. The idea is that we want to ignore certain things by default, like `node_modules` when running `gro serve`, so now that happens, without changing other external behavior.

add optional filer filter

---

changelog.md
src/client/GroDevtools.ts
src/server/server.ts
src/version.task.ts

This adds a confirmation prompt to the `gro version` task.
- expects a consistent subheading style in `/changelog.md`, e.g. `"## 0.1.9"` at the top should be the target of the version bump
- expects a valid version key in `package.json` (`npm init` and other tools add this key by default)
- expects the changelog version to be different than the package version
- add flags to override checks (problem is it currently forwards all args to `npm version`: "force" conflicts for example)
- check that the version increment matches the different between the changelog and package, when it's one of the normally computable kinds (the tiny library [lukeed/semiver](https://github.com/lukeed/semiver) could check that it's larger at least)

add version task confirmation prompt

---

changelog.md
src/build.task.ts
src/cert.task.ts
src/clean.task.ts
src/cli/invoke.ts
src/cli/types.ts
src/deploy.task.ts
src/dev.task.ts
src/format.task.ts
src/gen.task.ts
src/serve.task.ts
src/server/server.ts
src/task/README.md
src/task/invokeTask.ts
src/task/runTask.test.ts
src/task/runTask.ts
src/task/task.ts

This adds types for task args. Previously, it had no types, and we had a lot of type casting to compensate. Now, we have a good low-overhead pattern that lets external users import the `TaskArgs` interface type that each task exports by convention. (only those that actually need to; many or most don't need `args` types)

add task args types

---

changelog.md
src/build.task.ts

This fixes `gro build` to operate on only those build configs that have `dist true`. This allows a project's `src/gro.config.ts` to control the "last mile" each time `gro build` is run.
This was the documented behavior (see the config docs) but it wasn't properly implemented, so I'm considering it a patch fix.

filter build configs for the dist

---

README.md
changelog.md
src/build.task.ts
src/clean.task.ts
src/config/defaultBuildConfig.ts
src/docs/tasks.md
src/paths.ts
src/project/build.ts
src/serve.task.ts
src/server.task.ts
src/utils/log.ts
src/version.task.ts

This upstreams the `gro server` task first experimented with [here](https://github.com/ryanatkn/gro-template-sveltekit-polka) to combine SvelteKit and Gro projects. It's just a default and convention for projects that use the standard Gro/SvelteKit API server pattern, and may need to be redesigned to fit nicely.
One thing that still needs to be done is documentation of this emerging Gro API server convention. It's a convenient default to have for SvelteKit, easy to detect. False positives, like with Gro's own server, may be something to fix, or at least configure away properly.

add server task and build support

---

changelog.md
src/build.task.ts
src/build/postprocess.ts
src/build/utils.ts
src/config/config.ts
src/config/defaultBuildConfig.ts
src/config/gro.config.default.ts
src/dev.task.ts
src/docs/tasks.md
src/paths.ts
src/project/packageJson.ts
src/server.task.ts
src/start.task.ts
src/utils/module.ts
src/utils/path.test.ts
src/utils/path.ts

This adds the `gro start` task. If you know Gro you know that means there's now a `src/start.task.ts` file, assuming you didn't forget, which happens to everyone, even the best of robots. For now, `gro start` just tries to build if needed, and otherwise, it spawns an `npm start` with your args. I may change this before merging; I'm thinking of making it check for a series of paths to start (paths like the API server, the Node SvelteKit adapter, or really, paths derived from the config, and *not* being lazy with hardcoded defaults), then if none is found, bail with an error, never deferring to `npm start`, so users don't get used to that.
This PR also refactors some things around the API server. Previously we called it the "Gro server", now it's the "API server". I don't like the port …

add start task and refactor api server names

---

changelog.md
package.json

This updates the `package.json` engines property to `>=14.16.0`. We discovered some older v14 versions are broken, so we're standardizing here until the next version bump.

update node engine to >=14.16.0

---

changelog.md
src/build/externalsBuilder.ts
src/config/gro.config.default.ts

This fixes false positive API server detection in the default config. The API was originally sync I think, leading to a surprising but banal bug.

fix default config

---

changelog.md
src/build/Filer.ts
src/build/esbuildBuilder.ts
src/build/externalsBuilder.ts
src/build/svelteBuilder.ts
src/config/config.ts
src/fs/importTs.ts
src/project/build.ts
src/project/cssCache.ts
src/project/rollup-plugin-gro-esbuild.ts
src/project/rollup-plugin-gro-json.ts
src/project/rollup-plugin-gro-svelte.ts
src/project/rollup-plugin-gro-terser.ts
src/project/rollup-plugin-output-css.ts
src/project/rollup-plugin-plain-css.ts
src/server/server.ts
src/task/invokeTask.ts
src/task/runTask.ts
src/utils/log.ts
src/utils/process.ts

This improves the readability of the logging colors and gives us a standard helper for creating log labels, the prefixes before log statements. It's a small but nice improvement.

improve logging readability

---

changelog.md
src/config/buildConfig.ts
src/index.ts
src/utils/array.test.ts
src/utils/array.ts
src/utils/env.ts
src/utils/function.ts
src/utils/lazy.ts

It seems like we may want to export a number of things from the root. Soon, TypeScript 4.3 will deliver package exports support, so we can finally fix the `/dist/` import path wart into Gro's modules. This is a good time to start thinking about what the top-level API should include, thinking ahead to having good import paths as well.
For now we're mostly exporting just types.

export more things from root

---

changelog.md
src/project/build.task.ts
src/project/dist.task.ts
tsconfig.json

We have broken metadata in our build since we switched over to `esbuild`, since we were using its output artifacts in `dist/` instead of `tsc`. This should fix sourcemaps and typemaps, hopefully, by correctly prioritizing the TypeScript compiler's outputs over any . It's also cleaner and more correct - `tsconfig.json` points directly to `dist/` and knows nothing about Gro's internal build system - that was bad behavior, broken design.

fix dist build

---

changelog.md
src/build/externalsBuilder.ts
src/serve.task.ts
src/server/https.ts
src/server/server.ts
src/utils/env.ts

This renames the `process.env` helpers `stringFromEnv` and `numberFromEnv` to `toEnvString` and `toEnvNumber`.
Breaking because we expose our guts.

rename env helpers

---

README.md
changelog.md
src/build.task.ts
src/cert.task.ts
src/config/defaultBuildConfig.ts
src/deploy.task.ts
src/docs/README.md
src/docs/deploy.md
src/docs/tasks.md
src/fs/watchNodeFs.ts
src/start.task.ts
src/task/runTask.ts
src/version.task.ts

SvelteKit fits nicely with the deployment process we've been doing. Gro was building production artifacts to `dist/`, SvelteKit outputs to `build/`.
The trick now is to do the best integration with what `src/deploy.task.ts` was doing for our static deployments to GitHub Pages.
So far this PR:
- makes the build and deploy tasks work for SvelteKit projects
- adds custom `branch` CLI arg to both tasks
- adds the `clean` CLI arg to exit directly after cleaning up the git and Gro state
- adds the helper `hasSvelteKitFrontend` and uses it to try to do the right thing
- changes the deployment branch from `gh-pages` to `deploy` - we don't want to tie ourselves to GitHub, and now GitHub supports customizing the deployed branch name
- uses SvelteKit's `static/` to replace similar functionality we …

update build and deploy tasks to work with SvelteKit

---

changelog.md
src/build.task.ts
src/deploy.task.ts
src/fs/node.ts
src/paths.ts

There's a bug somewhere in the deploy script that's causing the commits to the deployment branch to fail. Was good to rewrite a lot of this. I was previously relying on some confusing git behavior, and the usage of the worktree is a bit more straightforward now, I think.
This also adds the `readDir` helper to `src/node/fs.ts`. The naming breaks convention with `readdir` in Node/`fs-extra`/Unix/etc but it aligns with the rest of the API - `emptyDir` and `ensureDir` are siblings for example, straight from our `fs-extra` library.

fix deploy task

---

changelog.md
src/build.task.ts

This is a quick fix for a little bug in the SvelteKit build. There's more that I may need to fix, but I may go to the source instead of patching. This was easy enough to do right now.

patch bug in SvelteKit with duplicate build dirs

---

changelog.md
src/build.task.ts
src/build/Filer.ts
src/build/externalsBuildHelpers.ts
src/build/externalsBuilder.ts
src/build/postprocess.ts
src/build/sourceFile.ts
src/config/config.ts
src/deploy.task.ts
src/fs/clean.ts
src/fs/inputPath.ts
src/paths.test.ts
src/paths.ts

This renames some constants to be consistent. It's great to know what a `dirname` *really* is.

rename some paths constants

---

changelog.md
src/build/Filer.ts
src/build/ServedDir.ts
src/build/postprocess.ts
src/build/sveltekit.ts
src/docs/config.md
src/fs/node.ts
src/project/packageJson.ts
src/project/rollup-plugin-plain-css.ts
src/serve.task.ts
src/server/server.ts
src/start.task.ts

This makes `gro start` work with production SvelteKit builds. Currently, `svelte-kit start` fails if projects define a `kit.paths.base` other than `'.'`  in their `svelte.config.cjs`, so we can't just defer to `svelte-kit` like with build and dev. We should be able to improve the API of `gro start` a bit to make this work.

make serve task work for production SvelteKit builds

---

changelog.md
src/build/Filer.ts
src/fs/watchNodeFs.ts
src/paths.ts
src/project/gitignore.test.ts
src/project/gitignore.ts

This makes `gro serve` use `.gitignore`, if it's available. It adds two helpers around `.gitignore`, `isGitignored` and `loadGitignoreFilter`. It loads once and caches, and is synchronous for convenience. (normally filesystem interactions would be async, but this is a special case for more general use cases in tools we don't control)

integrate gitignore with serve task

---

changelog.md
src/build/Filer.ts
src/build/esbuildBuildHelpers.ts
src/build/formatDirectory.ts
src/build/tsBuildHelpers.ts
src/config/config.ts
src/config/defaultBuildConfig.ts
src/fs/importTs.ts
src/paths.ts

This fixes `gro format` behavior when formatting `src/`. Previously, it detected that special condition and tried to format everything else in your project, which was the useful thing for our workflows. This switches that logic to use a whitelist, which allows us to opt into exactly the files we want to format outside of `src/`.

fix formatting

---

changelog.md
src/test.task.ts
src/version.task.ts

Currently, projects with no tests fail `gro check`. That can't be right. Also `gro version` should run `gro check` before running `gro build`.

fix tests when none are present

---

changelog.md
src/build.task.ts
src/build/utils.ts
src/dev.task.ts
src/paths.ts
src/project/build.ts

This changes `gro dev` and `gro build` with breaking interface changes. The goal is to unify as much of the API as possible with the `DevTaskContext` (better name?).

update dev and build tasks

---

changelog.md
src/start.task.ts

This fixes the `gro start` task to work with SvelteKit and the API server if detected.

fix start task

---

changelog.md
src/config/defaultBuildConfig.ts
src/start.task.ts

For static builds, `gro start` was serving on Gro's development ports; this aligns them with the other production builds on port 3000.

fix port for gro start on static builds

---

changelog.md
src/build/Filer.ts
src/build/FilerDir.ts
src/build/buildSourceDirectory.ts
src/client/SourceId.svelte
src/client/pathHelpers.ts
src/dev.task.ts
src/fs/file.ts
src/fs/filesystem.ts
src/fs/node.ts
src/fs/pathData.ts
src/fs/pathFilter.ts
src/fs/watchNodeFs.ts
src/project/gitignore.test.ts
src/project/gitignore.ts

This started out more ambitious but I ran into issues with gitignore. Eventually we'd like to abstract the filesystem from where the `Filer` uses `watchNodeFs` but until then we have this one corner of the app, gitignore, use the sync Node filesystem API.

fix gitignore and refactor filters

---

changelog.md
package.json
src/fs/testModule.ts
src/project/dist.task.ts

This fixes `npm link` for npm version 7. I'm totally stumped as to why this change is needed, and why it works just fine for the `esbuild` outputs but not `tsc`. I couldn't find any npm docs describing anything around this, except that `npm link` was rewritten for v7. Hopefully this fix is stable.

fix npm link

---

changelog.md
src/fs/testModule.ts
src/project/dist.task.ts
tsconfig.json

This refactors how Gro creates its production build. It fixes an issue where non-dist files were being included.

refactor gro prod build

---

changelog.md
contributing.md
src/deploy.task.ts

This fixes the `gro deploy` task in situations where your local `deploy` branch exists but is behind the remote. It should now `git pull` first from the remote.

fix deploy to pull the remote branch

---

README.md
changelog.md
src/build.task.ts
src/build/Filer.ts
src/build/dist.ts
src/build/utils.ts
src/config/buildConfig.ts
src/fs/filesystem.ts
src/project/dist.task.ts
src/start.task.ts

This appears to be a regression that appeared when we integrated SvelteKit. I'm not 100% sure how `dist/` should work in the build, but this seems stable enough, I think.

fix build to copy files to dist

---

README.md
changelog.md
src/clean.task.ts
src/docs/tasks.md

This reworks the `gro clean` task to have human-readable args. It also adds the `--git` option, so `gro clean --git`, to prune dead git branches. (be careful!)
It's technically a breaking change so up to 21 we go.

rework gro clean

---

changelog.md
src/gen.task.ts
src/gen/runGen.ts

This makes `gro gen` pass through files that fail to format. It'll log the best error it can.

change gro gen to handle failed formatting gracefully

---

changelog.md
src/deploy.task.ts

This allows the `gro deploy` `git pull` attempt to fail. The branch may not exist!

ignore error on failed git pull during deploy

---

changelog.md
src/deploy.task.ts

I think this is the desired behavior. Maybe we need an optional override. We treat the `deploy` branch as disposable, so I see no harm.

force push to deploy branch

---

changelog.md
src/index.ts

pretty self explanatory - this was intended to be public API, and we're moving away from deep imports (until **the typescript feature** lands)

export config from root

---

README.md
changelog.md
src/build/postprocess.ts
src/docs/philosophy.md

This is adds support for extensionless import paths for internal TS/JS modules, like `import from './to/thing'`. Currently, Gro only supports `'./to/thing.js'`.
This does not apply to external modules, those imported with a bare specifier like `import from 'svelte/store'` and their internal imports.
I've been resisting this change, because it's off-spec; ESM requires a file extension, and Gro has always gone all-in on ESM. So it feels wrong, but I think we have no choice if we want interop with SvelteKit/Vite:
The problem is a combination of TypeScript (issues/38149) and Vite (issues/61) behavior. (not linking because of backlink spam)
So which tool is really *wrong* here? I'm not really sure the spec has a good answer for this combination of tools. I currently believe I'd want to change …

support extensionless imports to internal modules temporarily

---

changelog.md
package-lock.json
package.json
src/build/Filer.test.ts
src/build/Filer.ts
src/build/sourceMeta.ts
src/fs/filesystem.ts
src/fs/importTs.ts
src/fs/memory.test.ts
src/fs/memory.ts
src/fs/node.ts
src/gen.task.ts
src/project/rollup-plugin-output-css.ts

This renames the filesystem helper `outputFile` to `writeFile`. It's just an aesthetic choice (I think `read/write` is better than `read/output` for most people), and it's a non-goal to conform to the `fs-extra` interface. (the semantics of `fs-extra` are the source of truth for Gro's `Filesystem`, but Gro changes names and owns the external interface)

rename Filesystem.writeFile from outputFile

---

src/check.task.ts
src/deploy.task.ts
src/publish.task.ts

I ran into at least a couple issues with #189. The first bug I found is related to arg forwarding - `gro gen` was being invoked from `gro publish <version>` and receiving its `version` arg. Not intended! Something to be more mindful of, and maybe improve with patterns or helpers.

fix gro publish

---

README.md
changelog.md
src/adapt/gro-adapter-spa-frontend.ts
src/build.task.ts
src/build/dist.ts
src/build/esbuildBuilder.ts
src/build/tsBuildHelpers.ts
src/fs/testModule.ts
src/paths.ts

Continues the work in #194:
Punting on Svelte type generation for now. Here are some links for that:
- https://github.com/sveltejs/language-tools/tree/master/packages/svelte2tsx
- https://github.com/micha-lmxt/svelte-types-writer
- https://github.com/firefish5000/svelte2dts
- https://github.com/IBM/sveld
- https://github.com/material-svelte/material-svelte/tree/main/tools/svelte-type-generator

generate types for production builds

---

changelog.md
src/build/dist.ts

Typemaps mistakenly pointed to `.d.ts.map` files instead of `.ts`.

fix typemap source path

---

changelog.md
src/publish.task.ts

`gro publish` depends on `changelog.md` so this helps the user along.

improve publishing changelog UX

---

changelog.md
src/publish.task.ts

This fixes two issues with `gro publish`:
- `npm version` args no longer conflict with task args
- initialize scoped packages so npm will accept them

fix publish

---

changelog.md
src/config/config.ts
src/publish.task.ts

This is a breaking change that improves the default config. It now extends user config with the detected defaults, instead of a stripped down default.

extend config with detected defaults

---

changelog.md
src/build.task.ts
src/build/Filer.test.ts
src/build/buildFile.ts
src/build/sourceFile.ts
src/build/sourceMeta.ts
src/client/sourceTree.ts
src/fs/clean.ts

This adds a fix to the build task, cleaning the production builds, by first splitting the source meta for dev and prod.
We're sticking to the invariant that the `Filer` can run in one mode or the other, but not both. This simplifies a whole lot of things, and you can always run a dev and prod filer concurrently.

separate source meta for dev and prod

---

changelog.md
src/adapt/gro-adapter-node-library.ts
src/adapt/gro-adapter-spa-frontend.ts
src/adapt/gro-adapter-sveltekit-frontend.ts
src/fs/memory.test.ts
src/paths.ts
src/utils/path.ts

GitHub pages processes static deployments with Jekyll by default. Aside from being unnecessary, it also breaks things like any files or directories prefixed with an underscore. This PR adds functionality to the adapters to do this automatically, with configurable escape hatches.

add nojekyll for GitHub pages

---

changelog.md
src/deploy.task.ts

This makes `gro deploy` properly check the status of the git working directory. The old strategy had some weird issues. It's likely we'll want to extract this to a helper for other tasks in the future.

properly detect unclean git state for `gro deploy`

---

changelog.md
src/clean.task.ts
src/dev.task.ts
src/serve.task.ts

Currently `gro dev` is hardcoded to watch mode, but it can be nice to run `gro dev` and just see the outputs without needing to startup and close the server, so `gro dev --no-watch` should do the trick now.

add `no-watch` arg to `gro dev`

---

changelog.md
src/build/build_source.ts
src/build/dist.ts
src/build/esbuild_builder.ts
src/build/ts_build_helpers.ts
src/config/config.ts
src/docs/config.md
src/gro.config.ts
src/paths.ts

Adds the `typemap` option alongside `sourcemap` to the Gro config. This is the TypeScript `declarationMap` option renamed to fit Gro's conventions. (maybe not advisable, but I like it right now) Defaults to the opposite of sourcemaps: included in production but not development builds. We may want to change the `sourcemap` default to be always `true`, but for the current primary library usecase we're not shipping sourcemaps, but we *are* shipping typemaps for nice editor support. (e.g. `go to definition` jumps to the actual TypeScript source files)
Also adds the `types` option to the Gro config, defaulting to `false`. It's enabled project-wide, not per build config, because we build once with `tsc` and read from the cache. It's currently not designed for development usage -- watch mode …

add typemap config option

---

changelog.md
src/adapt/gro-adapter-node-library.ts
src/gro.config.ts
src/utils/package_json.ts

Updates the Node library adapter to infer `npm link` behavior from the `package.json`, rather than making it a configurable option.

infer npm link from package json

---

changelog.md
src/build/build_config.test.ts
src/build/build_config.ts
src/config/config.ts
src/config/gro.config.default.ts
src/dev.task.ts

Fixes a bug with build config inference. The system config is now a validation error for production builds instead of being silently filtered out. Like before, users do not need to manually include one, and it's discouraged to avoid mistakes.

fix build config validation and normalization

---

changelog.md
src/build.task.ts
src/dev.task.ts
src/plugin/plugin.ts
src/utils/gitignore.test.ts
src/utils/gitignore.ts

Refactors the usage of `Plugin` to a common manager class with structured methods for creation/setup/teardown, removing the copypasta between `gro dev` and `gro build`.

extract plugins class

---

changelog.md
src/adapt/utils.ts
src/build/default_build_config.ts
src/build/postprocess.ts
src/config/gro.config.default.ts
src/paths.test.ts
src/paths.ts
src/plugin/plugin.ts

Fixes types in the library adapter by parsing `import type` dependencies. It's not bulletproof because it just uses a regexp, but any issues it causes could be worked around easily. (e.g. changing multiline comments to single line will break the matcher on commented-out imports)
Due to the way the internals currently work, this include imported types as dependencies, *and*, incorrectly, their accompanying `.js` files. They shouldn't cause any harm, but it's a wart I want to fix. The proper fix will require changing the efficient-but-less-powerful handling of type dependencies.

fix library adapter types

---

changelog.md
package.json
src/adapt/gro-adapter-node-library.ts
src/adapt/utils.ts
src/gro.config.ts

Adds path rebasing to the library adapter, so the default SvelteKit convention prefixed with `lib/` gets flattened into the root directory. This keeps things simple, so the `exports` field of `package.json` map 1:1 to actual files, and so you can import modules in packages without any `lib/` namespacing.

add path rebasing to library adapter

---

changelog.md
src/adapt/gro-adapter-node-library.ts

Fixes the library adapter's `files` field in the final `package.json`.

fix library package paths

---

changelog.md
src/build.task.ts

For SvelteKit-only frontend projects we need the `gro build` task to bypass `build_source`, because it's currently throwing an error.

fix buildless builds

---

changelog.md
src/build/postprocess.ts

Fixes imports from absolute paths pointing to modules inside the current directory, adding the `./` prefix as required by ESM.

add relative path prefix to bare internal specifiers

---

changelog.md
src/build/postprocess.ts

Without this change Gro would try to parse `import(abc)`, where `abc` is a variable and not a string literal, as the module `b`. (because it blindly trimmed the first and last characters that were expected to be quotes) This makes it ignore non-literal dynamic imports.

fix import parsing to ignore non-literal dynamic imports

---

changelog.md
src/build/postprocess.ts

Without this, dynamic imports with valid string literals using backticks were ignored. Now it only ignores them if they include string interpolation with `${`.

fix dynamic import parsing to allow non-interpolated template string literals

---

changelog.md
src/adapt/gro_adapter_node_library.ts
src/build/Filer.ts
src/build/build_dependency.test.ts
src/build/build_dependency.ts
src/build/build_file.ts
src/build/default_build_config.ts
src/build/esbuild_build_helpers.ts
src/build/esbuild_builder.ts
src/build/postprocess.ts
src/build/source_meta.test.ts
src/build/svelte_build_helpers.ts
src/build/svelte_builder.ts
src/paths.test.ts
src/paths.ts

This makes Gro properly build Svelte for production. Following Svelte conventions, the library adapter now publishes Svelte source, deferring compilation to users.
There are two main limitations:
- Custom preprocessors are not supported.
- This does not handle outputting compiled Svelte in production. We'll address that in #231.
We may want to rework things to move the `postprocess` step to the builders themselves, and provide helpers to avoid verbosity. That would allow builders to determine for themselves how to resolve dependencies, and modularize the currently-hardcoded JS and Svelte postprocessing.

support uncompiled svelte in production builds

---

changelog.md
src/deploy.task.ts

Changes `gro deploy` to infer the default `dirname` if none is provided as an arg. First looks for `dist/svelte-kit`, then `dist/browser`, then throws an error. Probably want to extend this detection in the future.

infer deployment directory

---

changelog.md
src/adapt/gro_adapter_gro_frontend.ts
src/adapt/utils.ts
src/build/Filer.ts
src/build/default_build_config.ts
src/build/filer_dir.ts
src/fs/file.ts
src/fs/filesystem.ts
src/fs/filter.ts
src/fs/memory.ts
src/fs/mime.ts
src/fs/node.ts
src/fs/watch_node_fs.ts
src/utils/gitignore.ts

Consolidates and renames some filesystem filters and adds an optional filter to `gro_adapter_gro_frontend`. We can't know which Rollup plugins a user project may add, so we just expose the filter in the adapter to override the defaults.

rename id filters and add filter option to gro frontend adapter

---

changelog.md
src/build/postprocess.ts

Fixes production Gro frontend builds (with `gro_adapter_gro_frontend`, not SvelteKit) by deferring externals bundling solely to Rollup. Prebundling now occurs only in development builds.

prebundle externals only in development

---

changelog.md
src/plugin/gro_plugin_sveltekit_frontend.ts

Makes `gro dev` and `gro build` forward SvelteKit args to the `svelte-kit` CLI command in the plugin.

forward sveltekit args

---

changelog.md
src/build/postprocess.ts

Trying to improve the type import/export regexp to catch weird corner cases. We can't assume that e.g. Svelte files are formatted.
Merging this, but not too happy with the regexp as is -- I guess we'll revisit if something breaks!

improve type matcher regexp

---

changelog.md
src/build.task.ts
src/clean.task.ts
src/deploy.task.ts
src/fs/clean.ts
src/publish.task.ts
src/test.task.ts

This fixes an issue with `gro build` where it doesn't clean when called by itself. It did clean when called as part of `gro deploy` and `gro publish`, but now it uses an arg to make sure it's always clean.
Also renames `clean` to `clean_fs` to be less ambiguous and avoid naming clashes with the `clean` arg.

clean during build

---

README.md
changelog.md
contributing.md
src/config/gro.config.default.ts
src/dev.task.ts
src/docs/test.md
src/gro.config.ts
src/plugin/gro_plugin_api_server.ts
src/plugin/gro_plugin_dev_server.ts
src/plugin/gro_plugin_sveltekit_frontend.ts
src/plugin/plugin.ts
src/server/server.ts

The dev server is starting up when we don't need it, so this makes it a plugin that's conditionally included, like for Gro frontend builds.
followup TODOs:

make dev server a plugin

---

changelog.md
src/config/config.ts
src/docs/config.md
src/lib/main.test.ts
src/test.task.ts

This removes the `main_test` config option added in #259. I dislike the design and it doesn't solve installing sourcemaps when running specific tests. There are several ways to approach this problem but I'm not sure which one is best. Adding this main test file to user projects seems like an ill-advised hack though.

remove main_test config and behavior

---

changelog.md
src/config/gro.config.default.ts

Changes the defaults so the dev server plugin doesn't load during production builds.

fix dev server for prod

---

changelog.md
src/deploy.task.ts

Makes `gro deploy` safer by disallowing branches `'main'` and `'master'` by default. As implemented, `gro deploy` force pushes to the target deployment branch because it treats it as disposable, but this could mean drastic badness if the developer gets confused and unintentionally chooses `--branch main` or something. The flag `--force` overrides this restriction.

safe deploy to exclude main branches

---

README.md
changelog.md
package-lock.json
package.json
src/client/SourceMetaBuildsTable.svelte
src/typecheck.task.ts
svelte.config.js

Adds [`svelte-check` ](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check) as a new dependency and extends `gro typecheck` to call it. `gro check` calls `gro typecheck`, so it now ensures type errors in Svelte files are caught by CI before checking things in. (TypeScript doesn't check Svelte files)
Adds 48 dependencies to Gro's existing 91, which makes me want to fork and replace its heavy dependencies and maybe upstream, but we have more important things to do. This PR puts on some weight! But it makes using Gro significantly more convenient.
The downsides:
- more dependencies which means more possible bugs and security issues and more responsibility
- some install time and a little disk space
- Gro feels significantly heavier
Here's the stats:
```
before: 91 …
```

add svelte-check

---

changelog.md
src/adapt/groAdapterGenericBuild.ts
src/adapt/groAdapterNodeLibrary.ts
src/adapt/groAdapterSveltekitFrontend.ts
src/build.task.ts
src/deploy.task.ts
src/publish.task.ts
src/task/task.ts

Deletes `dist/` for tasks like build/deploy/publish -- we previously relied on adapters to clean up for themselves, but this change simplifies things for the normal case, avoiding surprising problems at the cost of disallowing partial builds.

clean dist for production builds

---

changelog.md
src/build/Filer.ts
src/build/sourceMeta.ts
src/utils/throttleAsync.test.ts
src/utils/throttleAsync.ts

There's a race condition with writing the source meta to disk. Hoping this fixes it; it's hard to replicate. Adds and tests the new utility `throttleAsync` to discard all but the first and last calls to a promise-returning function.

fix writing source meta concurrently

---

src/build/Filer.ts
src/utils/throttleAsync.test.ts
src/utils/throttleAsync.ts

Uses the `throttleAsync` helper added in #288 to build files. It changes some behavior in subtle ways; the quirks I think I've identified can be fixed with a higher level redesign of the build process. Gro originally started with a haphazard single-file build process; with frontend build externals we hacked in some M:N building, which was since replaced with SvelteKit/Vite, and now I think we'll do M:N but better designed.
Also fixes `delay` in the `throttleAsync` implementation and adds some related tests.

use throttleAsync in filer build

---

package-lock.json
package.json

Apparently #286 broke some things for dependent projects like felt-template. Npm seems to not correctly handle peer deps when linking -- or I'm doing something wrong (very possible) -- so I can't seem to test this before publishing. I may just have to cycle through some patch versions before fixing this. I may revert #286 if I can't figure it out quickly. It seems like it's related to esbuild.

attempt to fix deps

---

changelog.md
src/config/gro.config.default.ts

Sneaky bug wormed its way into breaking `gro gen` in unfortunate cases. This should send it to the compost pile of git history.

fix default config to build types only for production

---

changelog.md
src/check.task.ts
src/docs/tasks.md
src/lint.task.ts

Adds the `gro lint` task using ESLint and calls it from `gro check`. Similarly to `svelte-check`, Gro does not specify ESLint as a peer dependency, and it'll detect if it's available in `node_modules/` before trying to run it.

add lint task

---

changelog.md
src/check.task.ts
src/lint.task.ts
src/task/task.ts

Makes `gro check` fail on lint warnings, makes `gro lint` default to `src`, and passes through args to `gro lint` to `eslint`.

pass through args to eslint and fail check on warnings

---

changelog.md
src/check.task.ts

Adds the following opt outs to `gro check`, and moves linting to the last step to improve most dev usage:
- `no-typecheck`
- `no-test`
- `no-gen`
- `no-format`
- `no-lint`

add gro check opt-outs

---

changelog.md
src/task/task.ts

fix task name printing for task directories

---

changelog.md
src/gen/genSchemas.ts
src/gen/runGen.ts
src/utils/schema.ts

Currently, schema generation uses the default file resolution and tries to read from disk. We currently use schema refs with absolute paths like `/schemas/Thing.json` to ease composition as dependencies in other projects. This changes the default schema resolution to look through the schemas in memory, allowing schemas to reference each other with `$ref: '/schemas/Thing.json'`.

register gen schemas

---

changelog.md
src/gen.task.ts
src/task/invokeTask.ts
src/test.task.ts

This is a step towards removing Gro's build system. Gro was designed before fast TypeScript transpilers like `esbuild` and `swc` (we now use the former because of SvelteKit), but now that it's ~20-100x faster (in my tests, using 1 to 8 cores, respectively) there's little reason not to compile on the fly, because it makes the UX much better. Gro users shouldn't have to run `gro dev` all the time, and this is one step towards removing its build system altogether in favor of something like [`tsm`](https://github.com/lukeed/tsm).

always build before running tasks

---

changelog.md
src/adapt/groAdapterNodeLibrary.ts
src/adapt/utils.ts

Currently `gro build` copies the entire `src/` for typemap support (e.g. "Go to definition" goes to the TS source file, not the JS), and this changes it to only included the include TypeScript files.

build minimal src

---

changelog.md
src/typecheck.task.ts

Changes `gro typecheck` to always report both `tsc` and `svelte-check` errors instead of stopping when a `tsc` error is encountered.

improve typecheck reporting

---

changelog.md
src/config/config.ts
src/config/gro.config.default.ts
src/docs/adapt.md
src/docs/config.md
src/gro.config.ts

Changes the Gro config to be inline with SvelteKit and Vite, exporting a default instead of a `config` property.

change config to a default export instead of a `config` property

---

changelog.md
src/build/buildSource.ts
src/build/typescriptUtils.ts
src/typecheck.task.ts
src/utils/sveltekit.ts
tsconfig.json

Also fixes building so we can turn `skipLibCheck` off in user projects.

always run `svelte-kit sync` instead of checking for dir

---

changelog.md
src/typecheck.task.ts

`svelte-check` v3 no longer needs this

remove unnecessary tsconfig option to gro typecheck

---

src/build/buildSource.ts
src/task/invokeTask.ts

Sorry, I know this PR is coming from left field, but I was messing around with other deployment work & finally got annoyed enough to wade into `gro` 😅 
It downgrades a few log entries from `info` into `debug` around the core `buildSource`, since I was finding them kind of noisy as part of our build & deploy pipeline upstream in Felt.
I'm open to other avenues if you think semantically these lines should still be at the `info` level. I could take another pass but this time with a `verbose` or `suppress` CLI arg for hiding them instead if you'd prefer?
lmk what you think! Also the README docs worked great for local development! 🎉

Set noisy build messages to debug level

---

.changeset/config.json
package-lock.json
package.json
src/docs/publish.md

`@svitejs/changesets-changelog-github-compact` has an unexpected dependency on GitHub access tokens, so this reverts to the default.
I'll look at `@changesets/changelog-git` as a potential replacement once it's working, or maybe make a custom one.

fix changesets

---

.changeset/shy-peas-invent.md
CHANGELOG.md
src/docs/gen.md
src/gen/fixtures/someTestObject.schema.ts
src/gen/genSchemas.ts
src/gen/runGen.ts
src/task/logTask.ts
src/utils/schema.ts
src/utils/schemaHelpers.ts

"vocab" is something that's app-specific, and Gro's schemas are any JSONSchema, so this corrects a misnomer.

rename VocabSchema to JsonSchema

---

.changeset/little-frogs-reflect.md
.changeset/mighty-countries-shout.md
.github/workflows/check.yml
README.md
package-lock.json
package.json
src/lib/gro.ts
src/lib/package.ts

Node's helpfully giving the migration as a runtime warning, `--loader` is no longer the way to load the loader, `--import` with `register` is. (maybe loader isn't the right word any more?)

use `--import` instead of `--loader`

---

.changeset/many-paws-notice.md
.changeset/sharp-snails-shout.md
.changeset/tall-radios-push.md
src/lib/build.task.ts
src/lib/changeset.task.ts
src/lib/check.task.ts
src/lib/dev.task.ts
src/lib/sync.task.ts
src/lib/upgrade.task.ts

Seems like it's more convenient and less error prone to just make `gro sync` run `npm i` by default, it's fast when cached.

install by default in `gro sync`

---

.changeset/silver-suits-give.md
src/docs/config.md
src/lib/changeset.task.ts
src/lib/gro_config.ts
src/lib/gro_plugin_sveltekit_library.ts
src/lib/publish.task.ts
src/lib/reinstall.task.ts
src/lib/sync.task.ts
src/lib/upgrade.task.ts

Makes Gro compatible with non-npm package managers that have compatible `install` and `link` commands.

add `pm_cli` config
