changelog.md
src/utils/random.test.ts
src/utils/random.ts

Renames some helper functions to avoid abbreviation.

rename random utils

---

changelog.md
package-lock.json
package.json

Upgrades TypeScript minor version.

upgrade typescript dep

---

.github/workflows/nodejs.yml
src/utils/string.test.ts

✔️ ✅ ✔️✔️✔️✔️✔️✔️✔️✔️✔️✔️✔️✅✅
`npm run bootstrap` is what I've been using to get Gro ready for development on itself. Whenever I break something and `gro` stops working, that command resets everything. This is semi-documented in the readme under the "develop" heading.
copy/pasted from Felt otherwise

add github ci workflow

---

changelog.md
package-lock.json
package.json

This upgrades most dependencies including the peer versions. Shouldn't be breaking.

upgrade dependencies

---

changelog.md
package-lock.json
package.json
src/project/rollup-plugin-gro-terser.ts

This updates the `terser` dependency to its latest version. There was a small breaking change to account for.

update terser dependency

---

README.md
src/build/Filer.ts

This fixes an oversight during source file initialization. It also extracts a couple related helpers.

fix source file dependent init

---

README.md
changelog.md
src/build/Filer.ts
src/build/FilerDir.ts
src/build/externalsBuilder.ts
src/client/App.svelte
src/client/BuildId.svelte
src/client/FileTreeExplorerFile.svelte
src/client/FileTreeExplorerFolder.svelte
src/client/FileTreeExplorerNode.svelte
src/client/SourceId.svelte
src/client/SourceMetaBuildTree.svelte
src/client/SourceMetaBuildTreeExplorer.svelte
src/client/SourceMetaExpander.svelte
src/client/SourceMetaRaw.svelte
src/client/SourceMetaTable.svelte
src/client/SourceMetaTreeExplorer.svelte
src/client/fileTree.ts
src/client/sourceTree.ts
src/docs/README.gen.md.ts
src/docs/tasks.gen.md.ts
src/paths.test.ts
src/paths.ts
src/utils/path.test.ts
src/utils/path.ts

This implements the file tree explorer client component, and adds an experimental component, the "build tree explorer". Needs a better name.
This is an unfinished WIP but it's fine since the rough stuff is all on the client.

file and build tree explorers

---

changelog.md
package-lock.json
package.json
src/build/Filer.ts
src/build/buildFile.ts
src/build/buildSourceDirectory.ts
src/build/builder.ts
src/build/esbuildBuildHelpers.ts
src/build/externalsBuilder.ts
src/build/formatDirectory.ts
src/build/lazyBuilder.ts
src/build/sourceFile.ts
src/build/sourceMeta.ts
src/client/sourceTree.ts
src/config/buildConfig.ts
src/config/config.ts
src/fs/importTs.ts
src/paths.test.ts
src/paths.ts
src/project/build.task.ts
src/project/clean.ts
src/project/link.task.ts
src/server/server.ts
src/typecheck.task.ts

This fixes the production build for Gro itself. Enough has changed that I need to redesign some of `src/project/build.task.ts`.

fix prod build

---

changelog.md
package.json
src/config/config.ts
src/fs/modules.ts
src/gro.config.ts
src/paths.ts
src/task/invokeTask.ts
src/utils/print.ts

This fixes module import paths from the dist directory.

fix dist imports

---

changelog.md
src/paths.ts

This fixes the partial fix from #100. Gtg for 0.5 I think.

fix imports for external gro from dist

---

changelog.md
src/config/defaultBuildConfig.ts

i am tired and this is a mistake that you make when you're tttired

fix swapped api server ports

---

changelog.md
package-lock.json
package.json
src/build/Filer.ts
src/build/baseFilerFile.ts
src/build/defaultBuilder.ts
src/build/esbuildBuildHelpers.ts
src/build/esbuildBuilder.ts
src/build/externalsBuilder.ts
src/build/lazyBuilder.ts
src/build/sourceFile.ts
src/build/sourceMeta.ts
src/build/svelteBuilder.ts
src/config/config.ts
src/fs/inputPath.ts
src/project/rollup-plugin-gro-esbuild.ts
src/project/rollup-plugin-gro-svelte.ts
src/project/rollup-plugin-output-css.ts
src/server/server.ts
src/task/taskModule.ts

This upgrades Svelte to the latest version, fixing breaking type imports.

upgrade svelte

---

README.md
changelog.md
contributing.md

doing one more pass on the text

add contributing.md

---

changelog.md
src/config/buildConfig.ts
src/config/config.ts
src/config/defaultBuildConfig.ts
src/config/gro.config.default.ts
src/docs/config.md
src/gro.config.ts

This renames some types that were inconsistent.

rename two partial types

---

package-lock.json
src/build/externalsBuilder.ts

This updates the lockfile to v2 with npm 7.

update lockfile to v2

---

changelog.md
src/build.task.ts

This fixes a bug in the production builds. I didn't notice this sooner because of a difference in my local setup.

fix production builds

---

changelog.md
src/index.ts

This exports `UnreachableError` and some time utils.

export UnreachableError and time utils

---

changelog.md
src/check.task.ts
src/publish.task.ts
src/test.task.ts

This continues the fix in #190 with a better understanding of the problem.

fix arg forwarding

---

changelog.md
src/adapt/gro-adapter-node-library.ts
src/build.task.ts
src/build/dist.ts

This adds types to production bundled dists.

generate types for bundled production builds

---

changelog.md
src/clean.task.ts
src/paths.ts

This upgrades to the latest SvelteKit. Some things were renamed.

upgrade SvelteKit

---

changelog.md
src/adapt/gro-adapter-node-library.ts
src/adapt/gro-adapter-spa-frontend.ts
src/adapt/gro-adapter-sveltekit-frontend.ts
src/build/rollup.ts
src/build/rollup_plugin_diagnostics.ts
src/paths.ts

This makes the SvelteKit frontend adapter compose with others, like the library adapter.

fix sveltekit adapter

---

changelog.md
src/deploy.task.ts

Fixes a small mistake in path construction that caused `gro deploy` to fail.

fix deploy task

---

src/adapt/adapter.ts
src/adapt/gro-adapter-generic-build.ts
src/adapt/gro-adapter-node-library.ts
src/adapt/gro-adapter-spa-frontend.ts
src/adapt/gro-adapter-sveltekit-frontend.ts
src/build.task.ts

Extracts `Timings` to the `Adapter_Context`, simplifying the code within adapters while retaining access to timings. In a followup we'll do the same for `Task_Context`.

refactor adapter timings

---

changelog.md
src/build/default_build_config.ts
src/config/gro.config.default.ts
src/docs/config.md
src/plugin/gro_plugin_api_server.ts

Changes the default server to `src/lib/server/server.ts` from `src/server/server.ts` to match new conventions.

change default server path

---

changelog.md
package-lock.json
package.json

Upgrades to esbuild@0.12.15 which may cause breaking changes in outputs.

upgrade esbuild

---

src/build/gro_builder_default.ts
src/build/gro_builder_esbuild.ts
src/build/gro_builder_externals.ts
src/build/gro_builder_simple.ts
src/build/gro_builder_svelte.ts
src/build/rollup_plugin_gro_svelte.ts
src/build/rollup_plugin_gro_terser.ts
src/docs/options.md
src/fs/watch_node_fs.ts
src/paths.ts
src/server/server.ts

Cleans up a bunch of things around options handling in the simple cases.

simplify options pattern and update its docs

---

changelog.md
package-lock.json
package.json
src/build/Filer.ts
src/build/postprocess.ts

upgrades `es-module-lexer@0.7.1`

upgrade es-module-lexer

---

README.md
src/docs/README.md
src/docs/test.md

Adds some basic documentation around `gro test`.

add test docs

---

changelog.md
package-lock.json
package.json

I kind of don't know what I'm doing

add peer dependencies including `@types/source-map-support`

---

.github/workflows/check.yml
README.md
changelog.md
package.json

require node 16.6

---

changelog.md
src/adapt/adapt.ts
src/build/build_config.ts
src/docs/adapt.md
src/docs/config.md
src/docs/plugin.md
src/plugin/plugin.ts
src/task/README.md
src/task/task.ts

fix unsnakes

---

changelog.md
package-lock.json
package.json
src/build/rollup.ts
src/docs/build.md
src/docs/publish.md
src/publish.task.ts

upgrade deps

---

changelog.md
package-lock.json
package.json

Still not sure what the best way to use peer deps is. This should be more future-proof. Might not want them at all, not sure.

fix peer dep versions

---

changelog.md
src/build.task.ts
src/deploy.task.ts
src/plugin/groPluginSveltekitFrontend.ts
src/publish.task.ts
src/test.task.ts

`gro publish` broke from #284 and it seems it's a self hosting problem

fix publish

---

changelog.md
src/adapt/groAdapterSveltekitFrontend.ts
src/adapt/utils.ts

See comment in the implementation for more.

fix 404 page for GitHub pages with SvelteKit adapter

---

changelog.md
src/build/buildConfigDefaults.ts

add schema files to system build

---

package-lock.json
package.json
src/task/logTask.ts

then make a new release with the CLI updates

upgrade felt

---

changelog.md
src/deploy.task.ts

fix deploy when the deployment branch isn't loaded locally

---

changelog.md
src/deploy.task.ts

Fixes the bug where deploy fails if the local `deploy` branch doesn't exist yet.

fix deploy for unfetched branches

---

README.md
changelog.md
package-lock.json
package.json
src/adapt/adapt.ts
src/adapt/gro-adapter-generic-build.ts
src/adapt/gro-adapter-node-library.ts
src/adapt/gro-adapter-sveltekit-frontend.ts
src/bootstrap.js
src/build/groBuilderDefault.ts
src/build/groBuilderEsbuild.ts
src/build/groBuilderJson.ts
src/build/groBuilderNoop.ts
src/build/groBuilderSimple.ts
src/build/groBuilderSvelte.ts
src/build/postprocess.ts
src/build/utils.ts
src/docs/adapt.md
src/docs/config.md
src/docs/dev.md
src/docs/gen.md
src/docs/philosophy.md
src/docs/plugin.md
src/docs/publish.md
src/docs/sveltekit.md
src/docs/task.md
src/plugin/gro-plugin-api-server.ts
src/plugin/gro-plugin-sveltekit-frontend.ts
src/routes/+page.svelte
src/task/invokeTask.ts

see https://github.com/feltjs/felt-ui/pull/271

rename to feltjs

---

changelog.md
src/build.task.ts
src/task/runTask.ts

install before building

---

src/build/Filer.ts
src/build/buildDependency.ts
src/build/buildFile.ts
src/build/postprocess.ts
src/build/sourceFile.ts
src/build/sourceMeta.ts
src/build/utils.ts
src/fs/modules.ts
src/paths.ts

small improvement to types mostly for documentation reasons

add file id types

---

.changeset/config.json
package-lock.json
package.json

Trying to get a good changelog generator that doesn't require GitHub auth.
I may add a custom version of this, IDK - https://github.com/changesets/changesets/blob/main/packages/changelog-git/src/index.ts

add changelog-git

---

.changeset/metal-dodos-cheat.md
.changeset/moody-camels-deny.md
README.md
package-lock.json
package.json
src/lib/changeset.task.ts
src/lib/cli.ts
src/lib/deploy.task.ts
src/lib/format.task.ts
src/lib/git.ts
src/lib/gro_plugin_library.ts
src/lib/gro_plugin_server.ts
src/lib/gro_plugin_sveltekit_frontend.ts
src/lib/invoke.ts
src/lib/lint.task.ts
src/lib/paths.ts
src/lib/publish.task.ts
src/lib/typecheck.task.ts
src/routes/+page.svelte
src/static/.well-known/package.json

future
- extract this module to `@grogarden/util-git` after some fuz library/docs/orc things are in place

remove execSync usage

---

.changeset/rude-feet-search.md
src/lib/check.task.ts
src/lib/git.test.ts
src/lib/git.ts

CI keeps failing here - https://github.com/feltjs/felt/pull/922#issuecomment-1737870380
seems to be acting unexpectedly in CI, so I'm changing some things to hoist failure

fix git helpers for CI

---

.changeset/healthy-bananas-live.md
.github/workflows/check.yml
src/lib/check.task.ts
src/lib/git.test.ts
src/lib/git.ts

doesn't detect untracked files, was thinking it should

check clean workspace

---

.changeset/gold-apples-pull.md
README.md
src/lib/docs/publish.md
src/lib/gro.config.default.ts
src/lib/gro_plugin_library.ts
src/lib/gro_plugin_server.ts
src/lib/gro_plugin_sveltekit_frontend.ts
src/lib/input_path.ts
src/lib/paths.ts
src/lib/publish.task.ts
src/lib/sveltekit_config.ts
src/lib/task.ts

followup
- put package.json and/or SvelteKit config on task/plugin context?
- `// TODO @multiple get from the sveltekit config`

detect library by default by checking for @sveltejs/package

---

.changeset/hot-ducks-run.md
src/lib/esbuild_helpers.ts
src/lib/gro.ts
src/lib/input_path.test.ts
src/lib/loader.ts

support sourcemaps

---

.changeset/spotty-queens-begin.md
README.md
package.json
src/lib/docs/tasks.md
src/lib/gro.ts
src/lib/gro_helpers.ts
src/lib/loader.ts
src/lib/package.ts
src/lib/run.task.ts

Convenience task for running any file with the loader.

add `gro run` task

---

.changeset/curvy-birds-double.md
.changeset/mighty-starfishes-approve.md
.changeset/old-suns-confess.md
src/lib/build.task.ts
src/lib/deploy.task.ts
src/lib/docs/publish.md
src/lib/docs/task.md
src/lib/invoke_task.ts
src/lib/publish.task.ts
src/lib/release.task.ts
src/lib/run_task.ts

todo
- should `invoke_task` automatically forward the args unless we want to override?

improve args forwarding

---

.changeset/happy-feet-trade.md
package-lock.json
package.json
src/lib/args.ts
src/lib/changeset.task.ts
src/lib/check.task.ts
src/lib/deploy.task.ts
src/lib/esbuild_helpers.ts
src/lib/gen.task.ts
src/lib/gen.ts
src/lib/invoke_task.ts
src/lib/package.ts
src/lib/package_json.ts
src/lib/paths.ts
src/lib/publish.task.ts
src/lib/run.task.ts
src/lib/run_gen.ts
src/lib/run_task.ts
src/lib/task.ts
src/lib/task_logging.ts
src/lib/test.task.ts

Added in https://github.com/ryanatkn/belt/pull/29
See https://nodejs.org/docs/latest/api/util.html#utilstyletextformat-text

replace `kleur` with Node's `styleText`

---

.changeset/stupid-items-taste.md
.changeset/tall-fireants-buy.md
package-lock.json
package.json
src/docs/plugin.md
src/lib/package.ts
src/lib/package_json.test.ts
src/lib/package_json.ts
src/lib/resolve_node_specifier.test.ts
src/lib/resolve_node_specifier.ts
src/routes/+page.svelte

`resolve_exported_value` was just hacked together, target behavior should be - https://nodejs.org/api/packages.html#resolving-user-conditions

 upgrade `esm-env@1.1.4` from `1.0.0`
